<?php

use Illuminate\Database\Seeder;
use App\Banks;

class BankSeeder extends Seeder
{
    const DATA = [
        ["name"=>"ABN AMRO BANK N.V.","code"=>"307"],
        ["name"=>"AGRICULTURAL BANK OF CHINA LIMITED","code"=>"222"],
        ["name"=>"AIRSTAR BANK LIMITED","code"=>"395"],
        ["name"=>"ANT BANK (HONG KONG) LIMITED","code"=>"393"],
        ["name"=>"AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED","code"=>"152"],
        ["name"=>"BANCO BILBAO VIZCAYA ARGENTARIA S.A.","code"=>"147"],
        ["name"=>"BANCO SANTANDER S.A.","code"=>"267"],
        ["name"=>"BANGKOK BANK PUBLIC COMPANY LIMITED","code"=>"49"],
        ["name"=>"BANK J. SAFRA SARASIN AG","code"=>"278"],
        ["name"=>"BANK JULIUS BAER & CO. LIMITED","code"=>"320"],
        ["name"=>"BANK OF AMERICA, NATIONAL ASSOCIATION","code"=>"55"],
        ["name"=>"BANK OF BARODA","code"=>"259"],
        ["name"=>"BANK OF CHINA (HONG KONG) LIMITED","code"=>"12"],
        ["name"=>"BANK OF CHINA (HONG KONG) LIMITED","code"=>"14"],
        ["name"=>"BANK OF CHINA (HONG KONG) LIMITED","code"=>"19"],
        ["name"=>"BANK OF CHINA (HONG KONG) LIMITED","code"=>"26"],
        ["name"=>"BANK OF CHINA (HONG KONG) LIMITED","code"=>"30"],
        ["name"=>"BANK OF CHINA (HONG KONG) LIMITED","code"=>"31"],
        ["name"=>"BANK OF CHINA (HONG KONG) LIMITED","code"=>"33"],
        ["name"=>"BANK OF CHINA (HONG KONG) LIMITED","code"=>"36"],
        ["name"=>"BANK OF CHINA (HONG KONG) LIMITED","code"=>"64"],
        ["name"=>"BANK OF CHINA (HONG KONG) LIMITED","code"=>"70"],
        ["name"=>"BANK OF COMMUNICATIONS (HONG KONG) LIMITED","code"=>"382"],
        ["name"=>"BANK OF COMMUNICATIONS CO., LIMITED","code"=>"27"],
        ["name"=>"BANK OF EAST ASIA, LIMITED","code"=>"15"],
        ["name"=>"BANK OF INDIA","code"=>"58"],
        ["name"=>"BANK OF MONTREAL","code"=>"86"],
        ["name"=>"BANK OF NEW YORK MELLON","code"=>"139"],
        ["name"=>"BANK OF NOVA SCOTIA","code"=>"76"],
        ["name"=>"BANK OF SINGAPORE LIMITED","code"=>"272"],
        ["name"=>"BANK OF TAIWAN","code"=>"201"],
        ["name"=>"BANK SINOPAC","code"=>"241"],
        ["name"=>"BANK SINOPAC","code"=>"244"],
        ["name"=>"BARCLAYS BANK PLC","code"=>"74"],
        ["name"=>"BDO UNIBANK, INC.","code"=>"67"],
        ["name"=>"BNP PARIBAS","code"=>"56"],
        ["name"=>"BNP PARIBAS SECURITIES SERVICES","code"=>"275"],
        ["name"=>"CA INDOSUEZ (SWITZERLAND) SA","code"=>"339"],
        ["name"=>"CANADIAN IMPERIAL BANK OF COMMERCE","code"=>"92"],
        ["name"=>"CANARA BANK","code"=>"262"],
        ["name"=>"CATHAY BANK","code"=>"263"],
        ["name"=>"CATHAY UNITED BANK COMPANY, LIMITED","code"=>"236"],
        ["name"=>"CHANG HWA COMMERCIAL BANK, LIMITED","code"=>"206"],
        ["name"=>"CHIBA BANK, LIMITED","code"=>"170"],
        ["name"=>"CHINA BOHAI BANK CO., LIMITED","code"=>"361"],
        ["name"=>"CHINA CITIC BANK INTERNATIONAL LIMITED","code"=>"18"],
        ["name"=>"CHINA CITIC BANK INTERNATIONAL LIMITED","code"=>"51"],
        ["name"=>"CHINA CONSTRUCTION BANK (ASIA) CORPORATION LIMITED","code"=>"9"],
        ["name"=>"CHINA CONSTRUCTION BANK CORPORATION","code"=>"221"],
        ["name"=>"CHINA DEVELOPMENT BANK","code"=>"276"],
        ["name"=>"CHINA EVERBRIGHT BANK CO., LIMITED","code"=>"368"],
        ["name"=>"CHINA GUANGFA BANK CO., LIMITED","code"=>"359"],
        ["name"=>"CHINA MERCHANTS BANK CO., LIMITED","code"=>"238"],
        ["name"=>"CHINA MINSHENG BANKING CORP., LIMITED","code"=>"353"],
        ["name"=>"CHINA ZHESHANG BANK CO., LIMITED","code"=>"383"],
        ["name"=>"CHIYU BANKING CORPORATION LIMITED","code"=>"39"],
        ["name"=>"CHONG HING BANK LIMITED","code"=>"41"],
        ["name"=>"CHUGOKU BANK, LIMITED","code"=>"202"],
        ["name"=>"CIMB BANK BERHAD","code"=>"374"],
        ["name"=>"CITIBANK (HONG KONG) LIMITED","code"=>"250"],
        ["name"=>"CITIBANK, N.A.","code"=>"6"],
        ["name"=>"CMB WING LUNG BANK LIMITED","code"=>"20"],
        ["name"=>"COMMERZBANK AG","code"=>"97"],
        ["name"=>"COMMONWEALTH BANK OF AUSTRALIA","code"=>"153"],
        ["name"=>"COÖPERATIEVE RABOBANK U.A.","code"=>"183"],
        ["name"=>"CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK","code"=>"5"],
        ["name"=>"CREDIT INDUSTRIEL ET COMMERCIAL","code"=>"324"],
        ["name"=>"CREDIT SUISSE AG","code"=>"233"],
        ["name"=>"CTBC BANK CO., LIMITED","code"=>"229"],
        ["name"=>"DAH SING BANK, LIMITED","code"=>"40"],
        ["name"=>"DBS BANK (HONG KONG) LIMITED","code"=>"16"],
        ["name"=>"DBS BANK (HONG KONG) LIMITED","code"=>"32"],
        ["name"=>"DBS BANK (HONG KONG) LIMITED","code"=>"52"],
        ["name"=>"DBS BANK LIMITED","code"=>"185"],
        ["name"=>"DEUTSCHE BANK AKTIENGESELLSCHAFT","code"=>"54"],
        ["name"=>"DZ BANK AG DEUTSCHE ZENTRAL-GENOSSENSCHAFTSBANK, FRANKFURT AM MAIN","code"=>"113"],
        ["name"=>"E.SUN COMMERCIAL BANK, LIMITED","code"=>"243"],
        ["name"=>"EAST WEST BANK","code"=>"258"],
        ["name"=>"EFG BANK AG","code"=>"237"],
        ["name"=>"ERSTE GROUP BANK AG","code"=>"227"],
        ["name"=>"FAR EASTERN INTERNATIONAL BANK","code"=>"260"],
        ["name"=>"FIRST ABU DHABI BANK PJSC","code"=>"277"],
        ["name"=>"FIRST COMMERCIAL BANK, LIMITED","code"=>"203"],
        ["name"=>"FUBON BANK (HONG KONG) LIMITED","code"=>"128"],
        ["name"=>"FUSION BANK LIMITED","code"=>"391"],
        ["name"=>"HACHIJUNI BANK, LIMITED","code"=>"188"],
        ["name"=>"HANG SENG BANK, LIMITED","code"=>"24"],
        ["name"=>"HDFC BANK LIMITED","code"=>"308"],
        ["name"=>"HONG LEONG BANK BERHAD","code"=>"248"],
        ["name"=>"HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED","code"=>"4"],
        ["name"=>"HSBC BANK USA, NATIONAL ASSOCIATION","code"=>"106"],
        ["name"=>"HUA NAN COMMERCIAL BANK, LIMITED","code"=>"198"],
        ["name"=>"HUA XIA BANK CO., LIMITED","code"=>"386"],
        ["name"=>"ICBC STANDARD BANK PLC","code"=>"341"],
        ["name"=>"ICICI BANK LIMITED","code"=>"251"],
        ["name"=>"INDIAN OVERSEAS BANK","code"=>"50"],
        ["name"=>"INDUSTRIAL AND COMMERCIAL BANK OF CHINA (ASIA) LIMITED","code"=>"29"],
        ["name"=>"INDUSTRIAL AND COMMERCIAL BANK OF CHINA (ASIA) LIMITED","code"=>"72"],
        ["name"=>"INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED","code"=>"214"],
        ["name"=>"INDUSTRIAL BANK CO., LIMITED","code"=>"377"],
        ["name"=>"INDUSTRIAL BANK OF KOREA","code"=>"271"],
        ["name"=>"ING BANK N.V.","code"=>"145"],
        ["name"=>"INTESA SANPAOLO SPA","code"=>"161"],
        ["name"=>"JPMORGAN CHASE BANK, NATIONAL ASSOCIATION","code"=>"7"],
        ["name"=>"KBC BANK N.V.","code"=>"178"],
        ["name"=>"KEB HANA BANK","code"=>"46"],
        ["name"=>"KOOKMIN BANK","code"=>"381"],
        ["name"=>"LAND BANK OF TAIWAN CO., LIMITED","code"=>"264"],
        ["name"=>"LGT BANK AG","code"=>"342"],
        ["name"=>"LIVI BANK LIMITED","code"=>"388"],
        ["name"=>"MACQUARIE BANK LIMITED","code"=>"344"],
        ["name"=>"MALAYAN BANKING BERHAD","code"=>"63"],
        ["name"=>"MASHREQ BANK - PUBLIC SHAREHOLDING COMPANY","code"=>"379"],
        ["name"=>"MEGA INTERNATIONAL COMMERCIAL BANK CO., LIMITED","code"=>"242"],
        ["name"=>"MELLI BANK PLC","code"=>"254"],
        ["name"=>"MITSUBISHI UFJ TRUST AND BANKING CORPORATION","code"=>"138"],
        ["name"=>"MIZUHO BANK, LIMITED","code"=>"109"],
        ["name"=>"MORGAN STANLEY BANK ASIA LIMITED","code"=>"384"],
        ["name"=>"MOX BANK LIMITED","code"=>"389"],
        ["name"=>"MUFG BANK, LIMITED","code"=>"47"],
        ["name"=>"NANYANG COMMERCIAL BANK, LIMITED","code"=>"43"],
        ["name"=>"NATIONAL AUSTRALIA BANK LIMITED","code"=>"150"],
        ["name"=>"NATIONAL BANK OF PAKISTAN","code"=>"60"],
        ["name"=>"NATIXIS","code"=>"210"],
        ["name"=>"NATWEST MARKETS PLC","code"=>"8"],
        ["name"=>"O-BANK CO., LIMITED","code"=>"274"],
        ["name"=>"OCBC WING HANG BANK LIMITED","code"=>"35"],
        ["name"=>"OCBC WING HANG BANK LIMITED","code"=>"44"],
        ["name"=>"OVERSEA-CHINESE BANKING CORPORATION LIMITED","code"=>"22"],
        ["name"=>"PHILIPPINE NATIONAL BANK","code"=>"119"],
        ["name"=>"PICTET & CIE (EUROPE) S.A.","code"=>"357"],
        ["name"=>"PING AN BANK CO., LIMITED","code"=>"385"],
        ["name"=>"PING AN ONECONNECT BANK (HONG KONG) LIMITED","code"=>"392"],
        ["name"=>"PT. BANK NEGARA INDONESIA (PERSERO) TBK.","code"=>"66"],
        ["name"=>"PUBLIC BANK (HONG KONG) LIMITED","code"=>"28"],
        ["name"=>"PUNJAB NATIONAL BANK","code"=>"266"],
        ["name"=>"QATAR NATIONAL BANK (Q.P.S.C.)","code"=>"394"],
        ["name"=>"ROYAL BANK OF CANADA","code"=>"80"],
        ["name"=>"SHANGHAI COMMERCIAL & SAVINGS BANK, LIMITED","code"=>"269"],
        ["name"=>"SHANGHAI COMMERCIAL BANK LIMITED","code"=>"25"],
        ["name"=>"SHANGHAI PUDONG DEVELOPMENT BANK CO., LIMITED","code"=>"345"],
        ["name"=>"SHIGA BANK, LIMITED","code"=>"199"],
        ["name"=>"SHINHAN BANK","code"=>"273"],
        ["name"=>"SHIZUOKA BANK, LIMITED","code"=>"186"],
        ["name"=>"SKANDINAVISKA ENSKILDA BANKEN AB","code"=>"316"],
        ["name"=>"SOCIETE GENERALE","code"=>"81"],
        ["name"=>"STANDARD CHARTERED BANK","code"=>"249"],
        ["name"=>"STANDARD CHARTERED BANK (HONG KONG) LIMITED","code"=>"3"],
        ["name"=>"STATE BANK OF INDIA","code"=>"82"],
        ["name"=>"STATE STREET BANK AND TRUST COMPANY","code"=>"220"],
        ["name"=>"SUMITOMO MITSUI BANKING CORPORATION","code"=>"65"],
        ["name"=>"SUMITOMO MITSUI TRUST BANK, LIMITED","code"=>"371"],
        ["name"=>"SVENSKA HANDELSBANKEN AB (PUBL)","code"=>"165"],
        ["name"=>"TAI SANG BANK LIMITED","code"=>"61"],
        ["name"=>"TAI YAU BANK, LIMITED","code"=>"38"],
        ["name"=>"TAIPEI FUBON COMMERCIAL BANK CO., LIMITED","code"=>"239"],
        ["name"=>"TAISHIN INTERNATIONAL BANK CO., LIMITED","code"=>"245"],
        ["name"=>"TAIWAN BUSINESS BANK, LIMITED","code"=>"230"],
        ["name"=>"TAIWAN COOPERATIVE BANK, LIMITED","code"=>"265"],
        ["name"=>"TAIWAN SHIN KONG COMMERCIAL BANK CO., LIMITED","code"=>"337"],
        ["name"=>"TORONTO-DOMINION BANK","code"=>"85"],
        ["name"=>"UBS AG","code"=>"103"],
        ["name"=>"UCO BANK","code"=>"45"],
        ["name"=>"UNICREDIT BANK AG","code"=>"164"],
        ["name"=>"UNION BANCAIRE PRIVÉE, UBP SA","code"=>"309"],
        ["name"=>"UNION BANK OF INDIA","code"=>"268"],
        ["name"=>"UNITED OVERSEAS BANK LIMITED","code"=>"71"],
        ["name"=>"WELAB BANK LIMITED","code"=>"390"],
        ["name"=>"WELLS FARGO BANK, NATIONAL ASSOCIATION","code"=>"180"],
        ["name"=>"WESTPAC BANKING CORPORATION","code"=>"151"],
        ["name"=>"WOORI BANK","code"=>"118"],
        ["name"=>"YUANTA COMMERCIAL BANK CO., LIMITED","code"=>"378"],
        ["name"=>"ZA BANK LIMITED","code"=>"387"],
        ["name"=>"中國農業銀行股份有限公司","code"=>"222"],
        ["name"=>"天星銀行有限公司","code"=>"395"],
        ["name"=>"螞蟻銀行(香港)有限公司","code"=>"393"],
        ["name"=>"澳新銀行集團有限公司","code"=>"152"],
        ["name"=>"西班牙桑坦德銀行有限公司","code"=>"267"],
        ["name"=>"中國銀行(香港)有限公司","code"=>"12"],
        ["name"=>"中國銀行(香港)有限公司","code"=>"14"],
        ["name"=>"中國銀行(香港)有限公司","code"=>"19"],
        ["name"=>"中國銀行(香港)有限公司","code"=>"26"],
        ["name"=>"中國銀行(香港)有限公司","code"=>"30"],
        ["name"=>"中國銀行(香港)有限公司","code"=>"31"],
        ["name"=>"中國銀行(香港)有限公司","code"=>"33"],
        ["name"=>"中國銀行(香港)有限公司","code"=>"36"],
        ["name"=>"中國銀行(香港)有限公司","code"=>"64"],
        ["name"=>"中國銀行(香港)有限公司","code"=>"70"],
        ["name"=>"交通銀行(香港)有限公司","code"=>"382"],
        ["name"=>"交通銀行股份有限公司","code"=>"27"],
        ["name"=>"東亞銀行有限公司","code"=>"15"],
        ["name"=>"新加坡銀行有限公司","code"=>"272"],
        ["name"=>"臺灣銀行股份有限公司","code"=>"201"],
        ["name"=>"永豐商業銀行股份有限公司","code"=>"241"],
        ["name"=>"永豐商業銀行股份有限公司","code"=>"244"],
        ["name"=>"金融銀行有限公司","code"=>"67"],
        ["name"=>"國泰銀行","code"=>"263"],
        ["name"=>"國泰世華商業銀行股份有限公司","code"=>"236"],
        ["name"=>"彰化商業銀行股份有限公司","code"=>"206"],
        ["name"=>"渤海銀行股份有限公司","code"=>"361"],
        ["name"=>"中信銀行(國際)有限公司","code"=>"18"],
        ["name"=>"中信銀行(國際)有限公司","code"=>"51"],
        ["name"=>"中國建設銀行(亞洲)股份有限公司","code"=>"9"],
        ["name"=>"中國建設銀行股份有限公司","code"=>"221"],
        ["name"=>"國家開發銀行","code"=>"276"],
        ["name"=>"中國光大銀行股份有限公司","code"=>"368"],
        ["name"=>"廣發銀行股份有限公司","code"=>"359"],
        ["name"=>"招商銀行股份有限公司","code"=>"238"],
        ["name"=>"中國民生銀行股份有限公司","code"=>"353"],
        ["name"=>"浙商銀行股份有限公司","code"=>"383"],
        ["name"=>"集友銀行有限公司","code"=>"39"],
        ["name"=>"創興銀行有限公司","code"=>"41"],
        ["name"=>"花旗銀行（香港）有限公司","code"=>"250"],
        ["name"=>"花旗銀行","code"=>"6"],
        ["name"=>"招商永隆銀行有限公司","code"=>"20"],
        ["name"=>"澳洲聯邦銀行","code"=>"153"],
        ["name"=>"法國工商銀行","code"=>"324"],
        ["name"=>"中國信託商業銀行股份有限公司","code"=>"229"],
        ["name"=>"大新銀行有限公司","code"=>"40"],
        ["name"=>"星展銀行(香港)有限公司","code"=>"16"],
        ["name"=>"星展銀行(香港)有限公司","code"=>"32"],
        ["name"=>"星展銀行(香港)有限公司","code"=>"52"],
        ["name"=>"玉山商業銀行股份有限公司","code"=>"243"],
        ["name"=>"華美銀行","code"=>"258"],
        ["name"=>"瑞士盈豐銀行股份有限公司","code"=>"237"],
        ["name"=>"遠東國際商業銀行股份有限公司","code"=>"260"],
        ["name"=>"第一商業銀行股份有限公司","code"=>"203"],
        ["name"=>"富邦銀行(香港)有限公司","code"=>"128"],
        ["name"=>"富融銀行有限公司","code"=>"391"],
        ["name"=>"恒生銀行有限公司","code"=>"24"],
        ["name"=>"豐隆銀行有限公司","code"=>"248"],
        ["name"=>"香港上海滙豐銀行有限公司","code"=>"4"],
        ["name"=>"美國滙豐銀行","code"=>"106"],
        ["name"=>"華南商業銀行股份有限公司","code"=>"198"],
        ["name"=>"華夏銀行股份有限公司","code"=>"386"],
        ["name"=>"中國工商銀行(亞洲)有限公司","code"=>"29"],
        ["name"=>"中國工商銀行(亞洲)有限公司","code"=>"72"],
        ["name"=>"中國工商銀行股份有限公司","code"=>"214"],
        ["name"=>"興業銀行股份有限公司","code"=>"377"],
        ["name"=>"意大利聯合聖保羅銀行股份有限公司","code"=>"161"],
        ["name"=>"比利時聯合銀行","code"=>"178"],
        ["name"=>"臺灣土地銀行股份有限公司","code"=>"264"],
        ["name"=>"麥格理銀行有限公司","code"=>"344"],
        ["name"=>"馬來亞銀行","code"=>"63"],
        ["name"=>"兆豐國際商業銀行股份有限公司","code"=>"242"],
        ["name"=>"摩根士丹利銀行亞洲有限公司","code"=>"384"],
        ["name"=>"南洋商業銀行有限公司","code"=>"43"],
        ["name"=>"澳大利亞國民銀行","code"=>"150"],
        ["name"=>"國民西敏寺資本市場銀行有限公司","code"=>"8"],
        ["name"=>"王道商業銀行股份有限公司","code"=>"274"],
        ["name"=>"華僑永亨銀行有限公司","code"=>"35"],
        ["name"=>"華僑永亨銀行有限公司","code"=>"44"],
        ["name"=>"平安銀行股份有限公司","code"=>"385"],
        ["name"=>"平安壹賬通銀行(香港)有限公司","code"=>"392"],
        ["name"=>"大眾銀行(香港)有限公司","code"=>"28"],
        ["name"=>"加拿大皇家銀行","code"=>"80"],
        ["name"=>"上海商業儲蓄銀行股份有限公司","code"=>"269"],
        ["name"=>"上海商業銀行有限公司","code"=>"25"],
        ["name"=>"上海浦東發展銀行股份有限公司","code"=>"345"],
        ["name"=>"靜岡銀行","code"=>"186"],
        ["name"=>"法國興業銀行","code"=>"81"],
        ["name"=>"渣打銀行","code"=>"249"],
        ["name"=>"渣打銀行(香港)有限公司","code"=>"3"],
        ["name"=>"大生銀行有限公司","code"=>"61"],
        ["name"=>"大有銀行有限公司","code"=>"38"],
        ["name"=>"台北富邦商業銀行股份有限公司","code"=>"239"],
        ["name"=>"台新國際商業銀行股份有限公司","code"=>"245"],
        ["name"=>"臺灣中小企業銀行股份有限公司","code"=>"230"],
        ["name"=>"合作金庫商業銀行股份有限公司","code"=>"265"],
        ["name"=>"臺灣新光商業銀行股份有限公司","code"=>"337"],
        ["name"=>"裕信(德國)銀行股份有限公司","code"=>"164"],
        ["name"=>"大華銀行有限公司","code"=>"71"],
        ["name"=>"匯立銀行有限公司","code"=>"390"],
        ["name"=>"友利銀行","code"=>"118"],
        ["name"=>"元大商業銀行股份有限公司","code"=>"378"],
        ["name"=>"眾安銀行有限公司","code"=>"387"],
        ["name"=>"中国农业银行股份有限公司","code"=>"222"],
        ["name"=>"天星银行有限公司","code"=>"395"],
        ["name"=>"蚂蚁银行(香港)有限公司","code"=>"393"],
        ["name"=>"澳新银行集团有限公司","code"=>"152"],
        ["name"=>"西班牙桑坦德银行有限公司","code"=>"267"],
        ["name"=>"中国银行(香港)有限公司","code"=>"12"],
        ["name"=>"中国银行(香港)有限公司","code"=>"14"],
        ["name"=>"中国银行(香港)有限公司","code"=>"19"],
        ["name"=>"中国银行(香港)有限公司","code"=>"26"],
        ["name"=>"中国银行(香港)有限公司","code"=>"30"],
        ["name"=>"中国银行(香港)有限公司","code"=>"31"],
        ["name"=>"中国银行(香港)有限公司","code"=>"33"],
        ["name"=>"中国银行(香港)有限公司","code"=>"36"],
        ["name"=>"中国银行(香港)有限公司","code"=>"64"],
        ["name"=>"中国银行(香港)有限公司","code"=>"70"],
        ["name"=>"交通银行(香港)有限公司","code"=>"382"],
        ["name"=>"交通银行股份有限公司","code"=>"27"],
        ["name"=>"东亚银行有限公司","code"=>"15"],
        ["name"=>"新加坡银行有限公司","code"=>"272"],
        ["name"=>"台湾银行股份有限公司","code"=>"201"],
        ["name"=>"永丰商业银行股份有限公司","code"=>"241"],
        ["name"=>"永丰商业银行股份有限公司","code"=>"244"],
        ["name"=>"金融银行有限公司","code"=>"67"],
        ["name"=>"国泰银行","code"=>"263"],
        ["name"=>"国泰世华商业银行股份有限公司","code"=>"236"],
        ["name"=>"彰化商业银行股份有限公司","code"=>"206"],
        ["name"=>"渤海银行股份有限公司","code"=>"361"],
        ["name"=>"中信银行(国际)有限公司","code"=>"18"],
        ["name"=>"中信银行(国际)有限公司","code"=>"51"],
        ["name"=>"中国建设银行(亚洲)股份有限公司","code"=>"9"],
        ["name"=>"中国建设银行股份有限公司","code"=>"221"],
        ["name"=>"国家开发银行","code"=>"276"],
        ["name"=>"中国光大银行股份有限公司","code"=>"368"],
        ["name"=>"广发银行股份有限公司","code"=>"359"],
        ["name"=>"招商银行股份有限公司","code"=>"238"],
        ["name"=>"中国民生银行股份有限公司","code"=>"353"],
        ["name"=>"浙商银行股份有限公司","code"=>"383"],
        ["name"=>"集友银行有限公司","code"=>"39"],
        ["name"=>"创兴银行有限公司","code"=>"41"],
        ["name"=>"花旗银行（香港）有限公司","code"=>"250"],
        ["name"=>"花旗银行","code"=>"6"],
        ["name"=>"招商永隆银行有限公司","code"=>"20"],
        ["name"=>"澳洲联邦银行","code"=>"153"],
        ["name"=>"法国工商银行","code"=>"324"],
        ["name"=>"中国信托商业银行股份有限公司","code"=>"229"],
        ["name"=>"大新银行有限公司","code"=>"40"],
        ["name"=>"星展银行(香港)有限公司","code"=>"16"],
        ["name"=>"星展银行(香港)有限公司","code"=>"32"],
        ["name"=>"星展银行(香港)有限公司","code"=>"52"],
        ["name"=>"玉山商业银行股份有限公司","code"=>"243"],
        ["name"=>"华美银行","code"=>"258"],
        ["name"=>"瑞士盈丰银行股份有限公司","code"=>"237"],
        ["name"=>"远东国际商业银行股份有限公司","code"=>"260"],
        ["name"=>"第一商业银行股份有限公司","code"=>"203"],
        ["name"=>"富邦银行(香港)有限公司","code"=>"128"],
        ["name"=>"富融银行有限公司","code"=>"391"],
        ["name"=>"恒生银行有限公司","code"=>"24"],
        ["name"=>"丰隆银行有限公司","code"=>"248"],
        ["name"=>"香港上海汇丰银行有限公司","code"=>"4"],
        ["name"=>"美国汇丰银行","code"=>"106"],
        ["name"=>"华南商业银行股份有限公司","code"=>"198"],
        ["name"=>"华夏银行股份有限公司","code"=>"386"],
        ["name"=>"中国工商银行(亚洲)有限公司","code"=>"29"],
        ["name"=>"中国工商银行(亚洲)有限公司","code"=>"72"],
        ["name"=>"中国工商银行股份有限公司","code"=>"214"],
        ["name"=>"兴业银行股份有限公司","code"=>"377"],
        ["name"=>"意大利联合圣保罗银行股份有限公司","code"=>"161"],
        ["name"=>"比利时联合银行","code"=>"178"],
        ["name"=>"台湾土地银行股份有限公司","code"=>"264"],
        ["name"=>"麦格理银行有限公司","code"=>"344"],
        ["name"=>"马来亚银行","code"=>"63"],
        ["name"=>"兆丰国际商业银行股份有限公司","code"=>"242"],
        ["name"=>"摩根士丹利银行亚洲有限公司","code"=>"384"],
        ["name"=>"南洋商业银行有限公司","code"=>"43"],
        ["name"=>"澳大利亚国民银行","code"=>"150"],
        ["name"=>"国民西敏寺资本市场银行有限公司","code"=>"8"],
        ["name"=>"王道商业银行股份有限公司","code"=>"274"],
        ["name"=>"华侨永亨银行有限公司","code"=>"35"],
        ["name"=>"华侨永亨银行有限公司","code"=>"44"],
        ["name"=>"平安银行股份有限公司","code"=>"385"],
        ["name"=>"平安壹账通银行(香港)有限公司","code"=>"392"],
        ["name"=>"大众银行(香港)有限公司","code"=>"28"],
        ["name"=>"加拿大皇家银行","code"=>"80"],
        ["name"=>"上海商业储蓄银行股份有限公司","code"=>"269"],
        ["name"=>"上海商业银行有限公司","code"=>"25"],
        ["name"=>"上海浦东发展银行股份有限公司","code"=>"345"],
        ["name"=>"静冈银行","code"=>"186"],
        ["name"=>"法国兴业银行","code"=>"81"],
        ["name"=>"渣打银行","code"=>"249"],
        ["name"=>"渣打银行(香港)有限公司","code"=>"3"],
        ["name"=>"大生银行有限公司","code"=>"61"],
        ["name"=>"大有银行有限公司","code"=>"38"],
        ["name"=>"台北富邦商业银行股份有限公司","code"=>"239"],
        ["name"=>"台新国际商业银行股份有限公司","code"=>"245"],
        ["name"=>"台湾中小企业银行股份有限公司","code"=>"230"],
        ["name"=>"合作金库商业银行股份有限公司","code"=>"265"],
        ["name"=>"台湾新光商业银行股份有限公司","code"=>"337"],
        ["name"=>"裕信(德国)银行股份有限公司","code"=>"164"],
        ["name"=>"大华银行有限公司","code"=>"71"],
        ["name"=>"汇立银行有限公司","code"=>"390"],
        ["name"=>"友利银行","code"=>"118"],
        ["name"=>"元大商业银行股份有限公司","code"=>"378"],
        ["name"=>"众安银行有限公司","code"=>"387"],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Banks::updateOrCreate(self::DATA);
    }
}
